name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake pkg-config check libsubunit-dev cppcheck libsystemd-dev libgnutls28-dev libjansson-dev libcurl4-gnutls-dev libmicrohttpd-dev valgrind doxygen gnutls-bin
    - name: cppcheck
      run: cppcheck --force --enable=warning,missingInclude --error-exitcode=1 .
    - name: dependencies
      run: |
        cd /opt
        git clone https://github.com/babelouest/orcania.git
        git clone https://github.com/babelouest/yder.git
        git clone https://github.com/babelouest/ulfius.git
        mkdir build
        cd build
        
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ../orcania
        make
        sudo make install
        rm -rf *
        
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ../yder
        make
        sudo make install
        rm -rf *
        
        cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib ../ulfius
        make
        sudo make install
        rm -rf *
    - name: build
      run: |
        # prepare build folders
        mkdir build
        # build rhonabwy, run tests, build package
        cd build
        cmake -DBUILD_RHONABWY_TESTING=ON -DBUILD_RHONABWY_DOCUMENTATION=ON -DWITH_CURL=OFF ..
        make
        rm -rf *
        cmake -DBUILD_RHONABWY_TESTING=ON -DBUILD_RHONABWY_DOCUMENTATION=ON ..
        ../test/cert/create-cert.sh || (cat ../test/cert/certtool.log && false)
        ln -s ../test/cert/ .
        ln -s ../test/cookbook-master .
        ln -s ../test/ .
        make test || (cat Testing/Temporary/LastTest.log && false)
        make package
        make doc
        sudo make install
        sudo ldconfig
        # test rnbyc
        cd ../tools/rnbyc/
        make test
